@version 1

# CPU	MODULE			TYPE	MAGIC	[ARGS...]
# 单 CPU 多用户进程: user0, user1, user2 共 3 个 EL0 进程
0	user.elf:user0		3	0xc	1 10
0	user.elf:user1		3	0xc	2 10
0	user.elf:user2		3	0xc	3 10
0	module_foo.mo:foo	1	0xa	count=2 tick=10
