@version 1
@test registry
@test cpu_alive module=test_cpu_alive.mo timeout_ticks=100
@test ipi_delivery module=test_ipi_delivery.mo rounds=50 timeout_ticks=500
@test smp_tlb_remap module=test_tlb.mo rounds=50

# CPU	MODULE			TYPE	MAGIC	[ARGS...]
0	module_foo.mo:foo	1	0xa	count=2 tick=10
0	module_abi.mo:abi	1	0xb
0	user.elf:user0		3	0xc
