#!/bin/bash
# gen_kallsyms.sh — 从内核 ELF 提取全部函数符号,生成 C 符号表
# 用法: script/gen_kallsyms.sh bin-x86_64/kernel > obj-x86_64/generated/kernel/kallsyms_all.c
set -e

nm -n "$1" | awk 'BEGIN { n = 0 }
/ [Tt] / {
    name = $3
    if (name == "" || name ~ /^_Z/ || name ~ /^\./) next
    addr = $1
    if (addr in seen_addr || name in seen_name) next
    seen_addr[addr] = 1
    seen_name[name] = 1
    addrs[n] = addr
    names[n] = name
    n++
}

END {
    print "/* Auto-generated by gen_kallsyms.sh — DO NOT EDIT */"
    print "#include <stdint.h>"
    print ""
    printf "const int KALLSYMS_COUNT = %d;\n\n", n
    print "struct { uint64_t addr; const char *name; }"
    print "kallsyms_all[] = {"
    for (i = 0; i < n; i++) {
        comma = (i < n - 1) ? "," : ""
        printf "    { 0x%s, \"%s\" }%s\n", addrs[i], names[i], comma
    }
    print "};"
}'
